[project]
name = "nesspy-analysis"
version = "0.0.2"
description = "Analyze nesspy output files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
]
